# Generated by Django 4.1.7 on 2023-03-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MAIN_COURSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=30)),
                ("item_code", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("item_name", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity", models.CharField(max_length=30)),
            ],
        ),
    ]
