# Generated by Django 4.1.7 on 2023-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD_APP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_course",
            name="category",
            field=models.CharField(default="main-course", max_length=30),
            preserve_default=False,
        ),
    ]
