# Generated by Django 4.1.7 on 2023-03-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD_APP", "0002_main_course_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="main_course", name="uid",),
    ]
